version: '2'
services:
  back:
    build:
      context: apps/back
      target: dev
    command: npm run dev
    environment:
      - PORT=3000
    volumes:
      - ./apps/back:/app
    ports:
      - 3000:3000
      - 3001:3001
    links:
      - dictionnary

  dictionnary:
    build:
      context: apps/dictionnary
      target: dev
    command: npm run dev
    environment:
      - PORT=3010
    volumes:
      - ./apps/dictionnary:/app
    ports:
      - 3010:3010
      - 3011:3011

  app:
    build:
      context: apps/app
      target: dev
    command: bash -c "VUE_APP_API_ENDPOINT='http://localhost:3000' npm run dev"
    environment:
      - VUE_APP_API_ENDPOINT=http://localhost:3000
      - PORT=8080
    volumes:
      - ./apps/app:/app
    ports:
      - 8080:8080
