version: '2'
services:
  back:
    build: apps/back
    command: bash -c "NODE_ENV=production npm start"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./apps/back:/app
    ports:
      - 3000:3000
      - 3001:3001
    links:
      - dictionnary
  dictionnary:
    build: apps/dictionnary
    command: bash -c "NODE_ENV=production npm start"
    environment:
      - NODE_ENV=production
      - PORT=3010
    volumes:
      - ./apps/dictionnary:/app
    ports:
      - 3010:3010
      - 3011:3011
  app:
    build: apps/app
    command: bash -c "NODE_ENV=production npm start"
    environment:
      - VUE_APP_API_ENDPOINT=https://api.bombparty.william.to
      - PORT=80
    volumes:
      - ./apps/app:/app
    ports:
      - 80:80
