version: '2'
services:
  back:
    build: apps/back
    command: npm start
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./apps/back:/app
    ports:
      - 3000:3000
      - 3001:3001
  app:
    build: apps/app
    command: bash -c "npm start"
    environment:
      - BASE_URL=/bombparty
      - VUE_APP_API_ENDPOINT=http://178.62.12.76:3000
      - PORT=80
    volumes:
      - ./apps/app:/app
    ports:
      - 80:80
